django/elearning/elearning/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers

from students.views import student_detail
from api.views import UserViewSet
from courses.views import course_detail, course_list, course_add

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url('^', include('django.contrib.auth.urls'), namespace='auth'),

    url(r'^course_detail/(?P<pk>\d)/$', course_detail, name ='course_detail'),
    url(r'^course_add/$', course_add, name='course_add'),
    url(r'^student_detail/(?P<student_id>\d)/$', student_detail, name ='student_detail'),
    url(r'^api/', include(router.urls)),
    url(r'^$', course_list),
]

django/elearning/api/models.py
from django.db import models

# Create your models here.

django/elearning/courses/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

from students.models import User

class Course(models.Model):
    name = models.CharField(max_length=200)
    students = models.ManyToManyField(User)

    def get_absolute_url(self):
        return reverse('course_detail', args=(self.id, ))

    def __str__(self):
        return self.name

class Section(models.Model):
    course = models.ForeignKey(Course)
    title = models.CharField(max_length=100)
    number = models.IntegerField()
    text = models.TextField()

    class Meta:
        unique_together = ('course', 'number', )

    def __str__(self):
        return self.title

class Question(models.Model):
    section = models.ForeignKey(Section)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=1000)
    correct = models.BooleanField()

    def __str__(self):
        return self.text

class UserAnswer(models.Model):
    question = models.ForeignKey(Question)
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        unique_together = ('question', 'user', )

django/elearning/students/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

django/elearning/courses/forms.py
from django import forms
from courses.models import Course

class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['name', ]

django/elearning/api/views.py
from rest_framework import viewsets

from students.models import User
from api.serializers import UserSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.order_by('-date_joined')
    serializer_class = UserSerializer

django/elearning/courses/views.py
from django.shortcuts import render
from courses.models import Course
from courses.forms import CourseForm
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, CreateView, ListView

# def course_detail(request, course_id):
#     course = Course.objects.get(id=course_id)
#     return render(request,'courses/course_detail.html',
#     {
#         'course': course,
#     })

class CourseDetailView(DetailView):
    model = Course

course_detail = CourseDetailView.as_view()

class CourseListView(ListView):
    model = Course
    queryset = Course.objects.prefetch_related('students')

course_list = CourseListView.as_view()


# def course_list(request):
#     courses = Course.objects.prefetch_related('students')
#     return render(request, 'courses/courses_list.html',
#     {
#       'courses': courses,
#     })

def course_add(request):
    if request.POST:
        form = CourseForm(request.POST)
        if form.is_valid():
            new_course = form.save()
            return HttpResponseRedirect(new_course.get_absolute_url())
    else:
        form = CourseForm()
    return render(request, 'courses/course_form.html', {
        'form': form,
    })

django/elearning/students/views.py
from django.shortcuts import render
from students.models import User

def student_detail(request, student_id):
    student = User.objects.get(id=student_id)
    return render(request, 'students/student_detail.html', {
        'student': student,
    })

django/elearning/courses/templates/courses/course_detail.html
<h1>Course detail</h1>

<p>{{ course.name }}</p>

django/elearning/courses/templates/courses/course_form.html
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="caca">
</form>

django/elearning/courses/templates/courses/courses_list.html
{% block "content" %}
<div class="container">
    <div calss="row">
        <div class="col-xs-12">
            <h1>Course list</h1>
            <ol>
                {% for course in course_list %}
                <li><a href="{{ course.get_absolute_url }}">{{ course.name }}</a></li>
                <ul>
                {% for student in course.students.all %}
                <li>{{ student }}</li>
                {% endfor %}
                </ul>
                {% endfor %}
            </ol>
        </div>

    </div>

</div>
{% endblock %}

django/elearning/courses/templates/courses/hello.html
<p>Hello, {{ who|upper }}!</p>

<p> {% lorem %} </p>

{% comment %}
<p>test</p>
{% endcomment %}

django/elearning/students/templates/students/student_detail.html
<h1>Student detail</h1>

    <p>{{ student }}</p>

    <ul>
        {% for course in student.course_set.all %}
        <li>{{ course }}</li>
        {% endfor %}
    </ul>